name: NewRelic app ID fetcher
description: Fetches an existing app ID from NewRelic
branding:
  icon: arrow-down-circle
  color: gray-dark
author: Zijad Aljic
inputs:
  newrelicApiKey:
    description: NewRelic API Key of your account
    default: ""
  appName:
    description: The name of the application that is existing in NewRelic APM
    default: ''
  newrelicRegion:
    description: Region the NewRelic account is running in
    default: US
outputs:
  appID:
    description: App ID output
runs:
  using: docker
  image: Dockerfile
